[package]
name = "my-wasm-project"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = { version = "0.1", optional = true }

[dependencies.web-sys]
version = "0.3"
features = [
  'Window',
  'Document',
  'Element',
  'console',
  'HtmlElement',
  'MouseEvent',
  'Worker',
  'MessageEvent',
  'HtmlInputElement',
  'CanvasRenderingContext2d',
  'CssStyleDeclaration',
  'EventTarget',
  'HtmlCanvasElement',
  'Node',
]
[dependencies.js_sys]
version = "0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[build-dependencies]
pkg-config = "0.3"

[package.metadata.wasm-pack]
# 配置 WASM 包的元数据
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz"] 

[features]
default = ["console_error_panic_hook"]

[profile.release]
lto = true



