[package]
name = "rust-test"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.33.1"
slint = "1.12.0"
serialport = "4.0.0"

[build-dependencies]
slint-build = "1.11.0"
[profile.dev]
debug = true 