[workspace]
members = ["shared", "web"]
resolver = "2"

[build-dependencies]
cargo-make = "0.37"

[profile.dev]
incremental = true
build-override = { opt-level = 0 }

[profile.release]
lto = true
codegen-units = 250