

[tasks.dev]
command = "cargo"
args = ["run", "--bin", "app"]

[tasks.build]
command = "cargo"
args = ["build", "--bin", "app"]

[tasks.build_win]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-msvc", "--bin", "app"]

[tasks.dev_apk]
command = "cargo"
args = ["apk", "run", "--lib"]

[tasks.build_apk]
command = "cargo"
args = ["apk", "build", "--lib"]

[tasks.dev_web]
command = "miniserve"
args = ["--index", "test.html"]
dependencies = ["build_web"]

[tasks.build_web]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "target/pkg"]

[tasks.clean]
command = "cargo"
args = ["clean"]




# mac 依赖 create-dmg
# brew install create-dmg
[tasks.dmg]
command = "create-dmg"
args = [
  "--no-internet-enable", "\\",
  "--volname", "\"MyAppInstaller\"", "\\",
  "--volicon", "./assets/MyApp.icns", "\\",
  "--window-pos", "400 200",
  "--window-size", "660 400", "\\",
  "--icon", "./assets/MyApp.icns", "\\",
  "--icon-size", "100", "\\",
  "./dist/Installer.dmg", "\\",
  "../target/release/bundle/osx/MyApp.app",
  # "--app-drop-link", "500 185"
]

[tasks.pkg]
command = "pkgbuild"
args = [
  "--root", "../target/release/bundle/osx/",
  "--identifier", "com.apathyjade.app",
  "--version", "1.0",
  "--install-location", "/Applications",
  "MyApp.pkg"
]


# ------------- 分割
[tasks.msi]
command = "wix"
args = [
  "build",
  "-arch", "x64",
  "-o", "./dist/MyAppInstall.msi",
  "./config/Product.wxs",
  "./config/Components.wxs",
  "./config/Config.wxs",
  "./config/UI.wxs",
]
dependencies = ["build"]

[tasks.debug_msi]
command = "msiexec"
args = [
  "/i", "D:\\project\\github\\apathyjade\\slint\\pc\\dist\\MyAppInstall.msi", "/qn", "/l*vx", "D:\\project\\github\\apathyjade\\slint\\pc\\log.txt"
]

[tasks.sign]
command = "signtool"
args = [
  "sign",
  "/f", "./certs/MyCodeSignCert.pfx", "/p", "wxy0809",
  "/fd", "SHA256",
  "/t", "http://timestamp.digicert.com",
  "./dist/MyAppInstall.msi"
]