
# [build]
# 默认目标设置为 RISC-V 64位 Linux
# target = "riscv64gc-unknown-linux-gnu"
# 输出目录设置为 riscv-target
# target-dir = "target"

# # RISC-V 64位 Linux 目标的具体配置
# [target.riscv64gc-unknown-linux-gnu]
# # 指定交叉编译工具链
# linker = "riscv64-linux-gnu-gcc"
# ar = "riscv64-linux-gnu-ar"

# # 传递给 Rust 编译器的参数
# rustflags = [
#     # 代码生成选项
#     "-C", "target-cpu=rv64gc",
#     "-C", "target-feature=+m,+a,+f,+d,+c",
    
#     # 链接选项
#     "-C", "link-arg=-Wl,--as-needed",
#     "-C", "link-arg=-lm",  # 链接数学库
#     "-C", "link-arg=-ldl", # 链接动态链接库
    
#     # 代码优化相关
#     "-C", "relocation-model=pic",
# ]

# 命令别名
# [alias]
# b = "build"
# br = "build --release"
# r = "run"
# rr = "run --release"
# check-riscv = "check --target riscv64gc-unknown-linux-gnu"

# 配置依赖源（使用国内镜像加速）
# [source.crates-io]
# replace-with = "tuna"
# [source.tuna]
# registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

# 发布模式配置
# [profile.release]
# opt-level = 3
# lto = true
# codegen-units = 1
# debug = false
# strip = true