[build]
target = "x86_64-unknown-linux-ohos"

[target.x86_64-unknown-linux-ohos]
linker = "./ohos_linker.sh"
# linker = "/Users/jade/Library/OpenHarmony/Sdk/20/native/llvm/bin/clang++"
rustflags = [
    "-C", "link-arg=--sysroot=/Users/jade/Library/OpenHarmony/Sdk/20/native/sysroot",
    "-C", "link-arg=-L/Users/jade/Library/OpenHarmony/Sdk/20/native/sysroot/usr/lib/x86_64-linux-ohos",
    "-C", "link-arg=-lc",
    "-C", "link-arg=-ldl",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Wl,--allow-shlib-undefined",
]

[env]
CXX = "/Users/jade/Library/OpenHarmony/Sdk/20/native/llvm/bin/clang++"
CC = "/Users/jade/Library/OpenHarmony/Sdk/20/native/llvm/bin/clang"
CXXFLAGS = "--sysroot=/Users/jade/Library/OpenHarmony/Sdk/20/native/sysroot"
CCFLAGS = "--sysroot=/Users/jade/Library/OpenHarmony/Sdk/20/native/sysroot"
SLINT_NO_QT = "1"

