
import "./assets/fonts/AlibabaPuHuiTi/AlibabaPuHuiTi-3-45-Light.ttf";
import "./assets/fonts/AlibabaPuHuiTi/AlibabaPuHuiTi-3-55-Regular.ttf";
import "./assets/fonts/AlibabaPuHuiTi/AlibabaPuHuiTi-3-65-Medium.ttf";
import "./assets/fonts/AlibabaPuHuiTi/AlibabaPuHuiTi-3-75-SemiBold.ttf";
import "./assets/fonts/AlibabaPuHuiTi/AlibabaPuHuiTi-3-85-Bold.ttf";

export global FontWeight {
  in-out property<int> Light: 300;
  in-out property<int> Regular: 400;
  in-out property<int> Medium: 500;
  in-out property<int> SemiBold: 600;
  in-out property<int> Bold: 700;
}
