[tasks.bundle]
command = "cargo"
args = ["bundle", "--release", "--format",  "msi"]

[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.build_window]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-msvc"]

# window 依赖 WiX Toolset
# "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\signtool.exe"
# linux 依赖 linuxdeploy
[tasks.msi]
command = "wix"
args = [
  "build",
  "-arch", "x64",
  "-o", "./dist/MyAppInstall.msi",
  "./config/Product.wxs",
  "./config/Components.wxs",
  "./config/Config.wxs",
  "./config/UI.wxs",
]
dependencies = ["build"]

[tasks.debug_msi]
command = "msiexec"
args = [
  "/i", "D:\\project\\github\\apathyjade\\slint\\pc\\dist\\MyAppInstall.msi", "/qn", "/l*vx", "D:\\project\\github\\apathyjade\\slint\\pc\\log.txt"
]

[tasks.sign]
command = "signtool"
args = [
  "sign",
  "/f", "./certs/MyCodeSignCert.pfx", "/p", "wxy0809",
  "/fd", "SHA256",
  "/t", "http://timestamp.digicert.com",
  "./dist/MyAppInstall.msi"
]

# mac 依赖 create-dmg
# brew install create-dmg
[tasks.dmg]
command = "create-dmg"
args = [
  "--no-internet-enable", "\\",
  "--volname", "\"MyAppInstaller\"", "\\",
  "--volicon", "./assets/MyApp.icns", "\\",
  "--window-pos", "400 200",
  "--window-size", "660 400", "\\",
  "--icon", "./assets/MyApp.icns", "\\",
  "--icon-size", "100", "\\",
  "./dist/Installer.dmg", "\\",
  "../target/release/bundle/osx/MyApp.app",
  # "--app-drop-link", "500 185"
]

[tasks.pkg]
command = "pkgbuild"
args = [
  "--root", "../target/release/bundle/osx/",
  "--identifier", "com.apathyjade.app",
  "--version", "1.0",
  "--install-location", "/Applications",
  "MyApp.pkg"
]